# Generated by Django 3.1.7 on 2021-03-07 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('profile_image', models.ImageField(upload_to='profile_images')),
                ('profile_headline', models.CharField(max_length=100)),
                ('profile_description', models.TextField()),
                ('current_employer', models.CharField(max_length=100)),
                ('current_website', models.CharField(max_length=200)),
                ('current_city', models.CharField(max_length=100)),
                ('current_state', models.CharField(max_length=100)),
                ('current_country', models.CharField(max_length=100)),
                ('professional_services', models.CharField(max_length=100)),
                ('professional_specialist', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
