# Generated by Django 3.1.7 on 2021-03-10 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='url',
        ),
        migrations.AddField(
            model_name='company',
            name='slug',
            field=models.SlugField(default='na', unique=True),
        ),
    ]
